spring.datasource.backend.driver-class-name=org.postgresql.Driver
spring.datasource.backend.url=${DB_URL}
spring.datasource.backend.username=${DB_USER}
spring.datasource.backend.password=${DB_PWD}
spring.datasource.backend.liquibase.change-log=db/changelog/db.changelog-master.xml
spring.datasource.backend.liquibase.contexts=production

service.s3.account-id=${S3_ACCOUNT_ID}
service.s3.secret-key=${S3_ACCOUNT_KEY}
service.s3.bucket-name=${S3_BUCKET_NAME}

keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=employee
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.credentials.secret=${KEYCLOAK_SECRET_KEY}

bulk.max-request.post=1000
bulk.max-request.update=1000
bulk.max-request.delete=500

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.parser.allow-backslash-escaping-any-character=true

# extract

extract.request-timeout.minutes=${EXTRACT_MAX_TIMEOUT_MINUTES}

spring.kafka.topics.meta=${EXTRACT_KAFKA_TOPICS_META}

spring.kafka.properties.ssl.truststore.location=${EXTRACT_KAFKA_SSL_TRUSTSTORE_LOCATION}
spring.kafka.properties.ssl.cert.location=${EXTRACT_KAFKA_SSL_CERT_LOCATION}
spring.kafka.properties.ssl.truststore.password=${EXTRACT_KAFKA_SSL_TRUSTSTORE_PASSWORD}
spring.kafka.properties.security.protocol=${EXTRACT_KAFKA_SECURITY_PROTOCOL}
spring.kafka.properties.sasl.mechanism=${EXTRACT_KAFKA_SASL_MECHANISM}
spring.kafka.properties.serverHost=${EXTRACT_KAFKA_SERVER_HOST}
spring.kafka.properties.username=${EXTRACT_KAFKA_USERNAME}
spring.kafka.properties.password=${EXTRACT_KAFKA_PASSWORD}

extract.scheduler.jobExecutor.interval-in-cron=${EXTRACT_PIPELINE_SCHEDULER_JOB_EXECUTOR_CRON}
extract.scheduler.clearer.interval-in-cron=${EXTRACT_PIPELINE_SCHEDULER_CLEARER_CRON}
extract.scheduler.user.id=${EXTRACT_SCHEDULER_USER_ID}
extract.scheduler.enabled=true

spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 5MB
spring.servlet.multipart.enabled=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=none

management.endpoints.web.exposure.include=health,prometheus,metrics

debug=false
