apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key | toString | upper }}: {{ $value | toString |  b64enc }}
{{- end }}
